### ISSUE TITLE
No more data since 1-2 Weeks

### ISSUE THREAD

**Issue by clusterzx** [CharlesGillanders/homeassistant-alphaESS#114]
I am getting this error arround 6000times in the Logfile. It worked like a charm for multiple weeks before. But now randomly stopped working.

`1 ERROR (MainThread) [alphaess.alphaess] Cannot connect to host openapi.alphaess.com:443 ssl:default [Try again]
2024-06-15 06:59:55.132 ERROR (MainThread) [alphaess.alphaess] Error: Cannot connect to host openapi.alphaess.com:443 ssl:default [Try again] when calling https://openapi.alphaess.com/api/getEssList
2024-06-15 06:59:55.132 ERROR (MainThread) [alphaess.alphaess] 'NoneType' object is not iterable
2024-06-15 06:59:55.133 ERROR (MainThread) [custom_components.alphaess] Unexpected error fetching alphaess data: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 30, in _async_update_data
    jsondata: json = await self.api.getdata()
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/alphaess/alphaess.py", line 296, in getdata`

Is ist possible that the API changed something in the backend?

**Comment by CharlesGillanders** [comment]
I suspect that is not an API backend issue - the error is stating that your home assistant cannot connect to the openapi.alphaess.com server.  That's more likely to be a firewall or DNS issue in your own network.  

If you can get terminal access to your home assistant box (you may need to install a terminal add-on from the add-on store) then you can run curl with the openapi URL to see if basic connectivity is working correctly, you should get a response like this:

~ $ curl https://openapi.alphaess.com/
{"code":6012,"msg":"AppId is empty"}~ $
