### ISSUE TITLE
Failed to Initialise

### ISSUE THREAD

**Issue by strickersuk** [CharlesGillanders/homeassistant-alphaESS#128]
Seems to have stopped working this morning, cloud and app working fine.

The only log error I can see is:

TypeError: unsupported operand type(s) for -: 'str' and 'float'

**Comment by strickersuk** [comment]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/coordinator.py", line 84, in _async_update_data
    inverterdata["Solar to Load"] = _pv - _feedin
                                    ~~~~^~~~~~~~~

**Comment by suds32** [comment]
Same for me

**Comment by strickersuk** [comment]
I'll close this issue to prevent duplication.
