### ISSUE TITLE
AlphaESS contains no entities

### ISSUE THREAD

**Issue by darkpainy** [CharlesGillanders/homeassistant-alphaESS#139]
Hi, 

I have an issue where I re-added my AlphaESS integration, setup is successfull but there are no entities found.
In the log I see this error: (unexpected keyword arugment "model_id"

2024-10-18 11:57:21.755 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform alphaess
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'
2024-10-18 11:57:21.759 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up alphaess platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 616, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'
<img width="548" alt="image" src="https://github.com/user-attachments/assets/db70f5ee-1cce-49bd-8b8f-4eab1d4594cd">

**Comment by Poshy163** [comment]
This might be due to the flakyness with the API, are you able to use postman (the data collection is here: https://github.com/CharlesGillanders/alphaess-openAPI/blob/main/AlphaESS%20Open%20API.postman_collection.json)

and get me some of the results? typically that happens due to not being able to call `getEssList`

**Comment by dukevyner** [comment]
I'm having the exact same issue, please excuse the ignorance, how exactly do we "use poastman"?

**Comment by dukevyner** [comment]
> This might be due to the flakyness with the API, are you able to use postman (the data collection is here: https://github.com/CharlesGillanders/alphaess-openAPI/blob/main/AlphaESS%20Open%20API.postman_collection.json)
> 
> and get me some of the results? typically that happens due to not being able to call `getEssList`

i am still having this issue, i have tried reseting the api dev key, deleting and re adding it to th api site.
deleting and reinstalling HA, HACS, and the aplhaESS intigration.

i managed to figure out how to use the postman json.

my results for the getEssList are as follows:

`{
    "code": 200,
    "msg": "Success",
    "expMsg": null,
    "data": [
        {
            "sysSn": "ALD001122121035",
            "popv": 10570.00,
            "minv": "SMILE-G3-S5-INV",
            "poinv": 5.00,
            "cobat": 10.08,
            "mbat": "SMILE-G3-BAT-10.1P",
            "surplusCobat": 9.58,
            "usCapacity": 95.00,
            "emsStatus": "Normal"
        }
    ],
    "extra": null
}`

any insight as to how to resolve this issue would be greatly appreicated

**Comment by Poshy163** [comment]
what error are you receiving @dukevyner when you try to start up the integration? are you on 5.6.1 and is there any other errors within the log that is shown before this error is made? 

There may be an issue with getting the serial number, which is the model_id and then it "links" all the services from a single SN together, maybe one of the calls are failing for some reason in the integration

**Comment by dukevyner** [comment]
@Poshy163 thanks for the reply
Currently running 0.5.6.1
Intigration  completes showing "![success](https://github.com/user-attachments/assets/f0daed0f-f6c8-4344-983e-75aa66aad952)" after entering the appid and secret key

One entry is recorded with the appid as the name

However ![no devices](https://github.com/user-attachments/assets/9fdff17e-607f-4167-925a-dc352ad72e5e) or entities are added

(excuse the mobile away from home atm) 


There are 4 ![errors](https://github.com/user-attachments/assets/8c77dcdd-b22e-404a-bf01-bb1df201ebe3) logged
All recorded below in the order of which they occurred 

```Logger: homeassistant.components.button
Source: helpers/entity_platform.py:580
integration: Button (documentation, issues)
First occurred: November 21, 2024 at 8:04:34 PM (28 occurrences)
Last logged: 12:33:21 PM

Error adding entity None for domain button with platform alphaess
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'
```

```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:580
integration: Sensor (documentation, issues)
First occurred: November 21, 2024 at 8:04:34 PM (136 occurrences)
Last logged: 12:33:21 PM

Error adding entity None for domain sensor with platform alphaess
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'
```

```
Logger: homeassistant.components.number
Source: helpers/entity_platform.py:580
integration: Number (documentation, issues)
First occurred: November 21, 2024 at 8:04:34 PM (8 occurrences)
Last logged: 12:33:22 PM

Error adding entity None for domain number with platform alphaess
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 580, in _async_add_entities
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 750, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'model_id'
```
```
Logger: homeassistant
Source: runner.py:147
First occurred: November 21, 2024 at 8:04:20 PM (6 occurrences)
Last logged: 12:33:22 PM

Error doing job: Unclosed client session
Error doing job: Unclosed connector
```

**Comment by Poshy163** [comment]
Interesting, 
when you are on PC, you should see some logs like this when you start up the integration. then a final data, are you able to take a screenshot of all of this (i have included what mine looks likes). it should be within the logs after you restart/enter in your info. then no entities appear.

![image](https://github.com/user-attachments/assets/cdec2ef6-1384-479d-9d83-2d142c72985a)

**Comment by dukevyner** [comment]
@Poshy163  interstingly mine is not showing the trying to call, parts but it is fetching some of the data including the serial and model
 
![image](https://github.com/user-attachments/assets/2cda4268-a43c-4fd9-b56c-1fc14cca9668)
![image](https://github.com/user-attachments/assets/41d957eb-f964-404f-9ffe-58dafc96c6b4)

the main errors repet a few times after this with no change

**Comment by dukevyner** [comment]
@Poshy163 sorry, clearly i had not enabled logging, figruing this out as we go. here is what you actually wanted
![image](https://github.com/user-attachments/assets/dee47157-d5b2-4034-9542-34e27634cb05)
