### ISSUE TITLE
AlphaEss Integration cant be configured on Synology DS923+ anymore but on DS216+

### ISSUE THREAD

**Issue by wace70** [CharlesGillanders/homeassistant-alphaESS#93]
Hi Charles, 

I opened some days before an issue.
I tested many things and I can say, that the fails everytime and only if I try it on my DS923+ (Ryzen CPU)
If I configure it on my old DS216+ (Intel CPU) it works like a charm.

If I copy the whole HA folder from the DS216+ to the DS923+ and start the HA, the AlphaEss integration gives me the same error message as I would install it.

Error:  Unknown error occurred

Can you telll me if the CPU has any releavation?

**Comment by johnbur1** [comment]
To confirm, I have it running on DS923+ fine

**Comment by wace70** [comment]
Here my log files (keep in mind that this pycache file is not in my installation!)

[Fri, 08 Dec 2023 12:26:42] DEBUG [selector_events.py.__init__:54] Using selector: EpollSelector
[Fri, 08 Dec 2023 12:26:42] DEBUG [apitest.py.main:24] instantiating Alpha ESS Client
[Fri, 08 Dec 2023 12:26:42] DEBUG [alphaess.py.getESSList:43] Trying to call https://openapi.alphaess.com/api/getEssList
[Fri, 08 Dec 2023 12:26:43] ERROR [alphaess.py.__get_data:249] Unexpected json_response : {'code': 6006, 'msg': 'Timestamp error'} when calling https://openapi.alphaess.com/api/getEssList
[Fri, 08 Dec 2023 12:26:43] ERROR [apitest.py.main:116] 'NoneType' object is not iterable
(venv) homeassistant-home-assistant1:/config/custom_components/alphaess/templib/alphaess-openAPI#

**Comment by CharlesGillanders** [comment]
@wace70 My apologies for the confusion - I don't need you to do anything other than increasing the logging in home assistant.  The relevant request was the one in the specific comment that I directed you to.  Just make sure that your homeassistant logs are cofigured to increase the verbosity for alphaESS - something like the following:

```
logger:
  default: info
  logs:
    custom_components.alphaess: debug
    alphaess.alphaess: debug
```

Once that is done, just restart HomeAssistant and try to configure the AlphaESS integration.  Send me the results of any AlphaESS log files from within HomeAssistant.

**Comment by wace70** [comment]
OK. I got here some Errros:


Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:403
First occurred: 14:29:10 (1 occurrences)
Last logged: 14:29:10

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alphaess/config_flow.py", line 57, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/alphaess/config_flow.py", line 28, in validate_input
    await client.authenticate()
  File "/usr/local/lib/python3.11/site-packages/alphaess/alphaess.py", line 323, in authenticate
    for unit in units:
TypeError: 'NoneType' object is not iterable



==================================
next error


Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: alphaess.alphaess
Source: custom_components/alphaess/config_flow.py:28
Integration: Alpha ESS (documentation, issues)
First occurred: 14:29:10 (2 occurrences)
Last logged: 14:29:10

Unexpected json_response : {'code': 6006, 'msg': 'Timestamp error'} when calling https://openapi.alphaess.com/api/getEssList
'NoneType' object is not iterable




================================

and here the whole protocol:



2023-12-08 13:29:09.594 DEBUG (MainThread) [alphaess.alphaess] Trying to call https://openapi.alphaess.com/api/getEssList
2023-12-08 13:29:10.273 ERROR (MainThread) [alphaess.alphaess] Unexpected json_response : {'code': 6006, 'msg': 'Timestamp error'} when calling https://openapi.alphaess.com/api/getEssList
2023-12-08 13:29:10.273 ERROR (MainThread) [alphaess.alphaess] 'NoneType' object is not iterable
2023-12-08 13:29:10.274 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alphaess/config_flow.py", line 57, in async_step_user
await validate_input(self.hass, user_input)
File "/config/custom_components/alphaess/config_flow.py", line 28, in validate_input
await client.authenticate()
File "/usr/local/lib/python3.11/site-packages/alphaess/alphaess.py", line 323, in authenticate
for unit in units:
TypeError: 'NoneType' object is not iterable


Hope this is useful

**Comment by CharlesGillanders** [comment]
There's a timestamp error coming back from alphaESS.  I suspect that the time on your home assistant VM might not be synchronized to a reliable source, are you using NTP on your new NAS?
